script: npm run build
language: node_js
node_js:
- '8'
env:
- BUILD_ENV=CI
cache:
  directories:
  - node_modules
notifications:
  webhooks: https://fathomless-fjord-24024.herokuapp.com/notify
deploy:
- provider: releases
  api_key:
    secure: Ewhvm/h+2y3uVIDrF9kbAFe3ayU6qxmbnA13HL74QCm46xuxzBcNT/d2hvJPjSKs4lS2DGr+S1WeALTlVPS14crQkeieq30MIYOVa1Zg22PaARQ8t3PmN9V8MJI9DMKfKbj4Dx2Ly+LdY1oRxChdNhFxJ3zF3E6ddPngyOjC5Tr7c0q/f2L7kLFhOIlrfY8BDno8MTb4a7QtiEhIIK2mSsmqpQJ+3G2Fa5UM+KHRF0RmJisNvHRz66MTVBjBBE3NpI1aoA6vjZwk2XQczvygqDrQ20GWTbW9dfZWte7vUzACNRjrSnZWK6MoCyxHpuxE5+PJ2rs5EnMHy2NBJRcfCDkU90xRYMKn7NAngHUQmHPdiyDNwhtnzRNtVtzdqfWJmCWFvLX3Z/NhJZ7sU9ET3ETfq5Qn6GNtGwhMCbLCNSkaWO1iECzzaC93z4hCLjoe2P4m2/CbFeiokuC6CbU8BiuWoLrReahi4vhka/a16jW42s02HnNaLieGdsh4te1x/zyhKp/ynT4OSFY0mxJNXjcLCoU4vxFuUvT7T0Uacuv5ZelaTx8yD7M07NhGPDdargqtz+p92ek6RDDjvV8I+C7TN6NVqm0yIowBHVadK1t1SXmd9HtRaZLrHLj4tc2CogWlVNrn80Gm60Xs/RuUgv0Dx4orNLmMrzYBG5k7Os4=
  file:
    - dist/ef-core.min.js
    - dist/ef-core.min.js.map
  skip_cleanup: true
  on:
    tags: true
- provider: npm
  email: syqlds@126.com
  api_key:
    secure: IYtA6evz3HQeKU8cekEyEdco6d5kboweJ/vlpFr+0aGWNp/Jcf4m722QpU04o3nJOla1x6Ji+5ZFZ4xg3uq+2OKsK9Qt+fbga/PrlPny4A4ifEJsekPg79yElZcGFI8Bxd8C03Yq2JxTtUuB5srkqedK954VEMOzozxplSG43H54o26QlgDyy9UfE1CgwRkvhR9qEXsDQOpWEdn/bZnym1GRX+GqArSFlplDSDKhtNMK7pZDhKngWgM8vJQTCxq9k5/o7Ef7RCm37/664xmWX2VBrz1j1gITKN0fbqKFyHhlqutrMIZaS1FtCrOWyklPQsVrvkRSlxNSIhQgiqos9tKPr1R7LwulrkW1xbmR5SF2p0HDXC9/3nitfxMM5C2wJBWb94K/z9MJOtjj5y8Kqqf8BOsFhN1DNgmFYinwovsTtOFY5di0XgF+Ye2c9Nf2ijCokjZvLoUaX92U9e+o8j7++ir2uuMG0ftzm4bdD3M/IqH9Byo0szvVzD20lnW2qJjRh3xjKVuDm2OavWrPd+Hz063M4UAhxqX8DuheR+oOub+1qHCwjAQQ1WtYf4KWOL+yF+nk2gW4afQxXWBMbNipHhmzdYWQzfYXrVcry3K8cke9kwEacyq8nCgvDEOBD2HQcEMaDDWqIXjYUPOdSHzZ+kQdsX3j0vrm81SVPHc=
  skip_cleanup: true
  on:
    branch: master
