script: npm run build
language: node_js
node_js:
- '8'
env:
- BUILD_ENV=CI
cache:
  directories:
  - node_modules
notifications:
  webhooks: https://fathomless-fjord-24024.herokuapp.com/notify
deploy:
- provider: releases
  api_key:
    secure: Y8GXHhdb2JueCYkKer9hm7lvHxQUltXjVxQc31dRuLDhxxX9nNYPHvu7CqN020LVglgB1r9XEmYA83M7KhT/U0BfSl/DY9/bGOp0udwHINqSjlVegrFJ0hLo+KVe1HA8zrI4kzm9mExzXu6I5VdP1YUls60VSI9o15g1WB49+rs/xkMCATf+zDzT1PGqs4rv8jXhCG7ZHs9aQba6GUDENBsfx+MQEryaFbGGXrG6684KxEwMaxclqZ4PSsOzX1yd6y2nKJDGSeNV+0+u4GX5IHfUd7gdLgu/SeBAIv4lc6B0ixY6PYnLNwXzMV231cWc28x2XSgeX8GyFl5rBX0WUwJHqyaqSED8iOcoxKZzSHMm/t6CL9lkBVXcKcrFgglhnCrD8kEsgrn7gHhFKCG8Yiwvg1XmXGt66TUz9u3mHM1juSQh7UpeYTOquprrp4kCN5FCQB7aO3496H/cMaMywCxtwXCgHalArtomXKmXpv1pHf8q/Lge+d9IwhD8YtuW/qJgMf9yzdUTHxt4wgy8TfQkOPBcxWgVYFV8IBFp6ceK11hNIyzYPULYW1JSrR8yw2l/nvvGBUPDlHDQMmKe6tKJHn9iMJQqOvpoIZz7kjKzUAKOplJNeGd/sIeAu/CweI86Sf0NwM7J3qs3Kj9SO0p2gTBqKbUjhee6+rTT3TU=
  file:
    - dist/ef-core.min.js
    - dist/ef-core.min.js.map
  skip_cleanup: true
  on:
    tags: true
- provider: npm
  email: syqlds@126.com
  api_key:
    secure: QQpIM5UF3UAXxoRT5vQQb9mw5i44KUfocfHkyFETH+YGD8cYy1Csqkt3+sTvaVeitSIeCifUGnIomcBlQf4w7Hl5GR7EB7CbtzqJKy4oXsnFxnRhNlSOWJcMgBQu4UQSpTrnpQvWb3t6ndXgRVhobBCKgj+v5O3ajJsjo6exWvRygb3T0pdcS9WUqK9xLaQ6spiy/OTcX8IHVzPbmC4+e7IR7S88VXEur7eq3k4UUOKktq6W7Wizf653VUH6S4a8LnHC+LqYWLBh+17J03CBhfoR8HLq1iF6E11R3erniOdPMxEQnAhgnY0VB3eabl1gZK2HwDzKS9hpffRDBqk1NkgfTbwCDQoPhTVPNixXGls4+3XgsbtjuiDidfzTW5qeHgooMxQeX0KTPtx6qNmeAgkz9BQEVJP80HwBjRAdQqE3nz4AYXq7dcKOo+UE+VYGhcXKgiFFD1Ct49xGq09v+QMuDc2p+fLC6NgPVeTG+AdVMQpMhRNOv1HeSZbzCOpAZpQnj+Z/6gbEPaLx6oeiNu59mduCCvID3xW//B5YzRDpgHFGEPA/ULJ0edld6UO5H2rj8VuTyOzpW7p6212RXA7HjmZ9OtWvSozet967Y+sMox48m6JKjOjZh0dRPysjeRJwhYwAUxllHHw7l6ZuvMXhssMZP7wGjmdyYM2ScFw=
  skip_cleanup: true
  on:
    branch: master
