script: npm run build
language: node_js
node_js:
- '8'
env:
- BUILD_ENV=CI
cache:
  directories:
  - node_modules
notifications:
  webhooks: https://fathomless-fjord-24024.herokuapp.com/notify
deploy:
  provider: npm
  email: syqlds@126.com
  api_key:
    secure: HG7p4W+fK7JUfhgTON7vgNSpc5kM2lPrxJqyu/xQyIxHXbxvRmIp9nmA4bZR0+159DsvwC+TITIWGKKrVjfImoyFsItLJOLZCNUBUlDtnR56LvmLBKbxw2qAcuV8Z2cHb0WPjOLmaR6jUmFy72yS7l714J0CXNPultOhNTv3i1+WYwagOOAT6YCPSbViP08pN2ELNBdd/Ti4u50Mm+0GKbtIIJk0If8RSlMnex9Tv7HCqemdu03VhgED7tKwibyfhK0D45kLLZ1sGwCbrzCl+9AKctvaaV+4/qf2DGo9BkunuMhObhr3OXiCMI+JtKbGhFRndVkhi3q+oKGkdAa793BhpMFdpVcm8XiE5rhqxhlttUrfZtXMcAVvVMVPNvycA77l4ZLpGRABhx/0ay+dqpUZhmpFfi9BovUeCSSd6cTZ0XsZOE3CbcC7QZcWNcq31LrW9y3t9t6Ch/tKai9Ge7fbvuemwUXs2x8gp3+mllBGODdc8mwgFJV2NXrQ8t253Zx3+J6gNPS9vCes30iWXIhKmLU0f9naRWrnrHM7zmZGzKKOWxV3sRfGt+tNQeAvDJ9U8J+tj1ITKYLxoVile8cZCLS3kY5drpYAJE17s+Mr3s0J4fF0SfCXZQVGh+a1W4x1WQgUuwEIN7xL9hdytISvYVR9oz7Xtk++sLKPadk=
  skip_cleanup: true
  on:
    branch: master
