script: npm run build && npm run prod
language: node_js
node_js:
- '9'
env:
- BUILD_ENV=CI
cache:
  directories:
  - node_modules
notifications:
  webhooks: https://fathomless-fjord-24024.herokuapp.com/notify
deploy:
- provider: releases
  api_key:
    secure: No2Y6g0dmjnMT2mHYjafM4VpEll8/NS9Yr9FG40A0tgHbyYaYO4PF7zo6tgsU6P5Z2yA+yhg26l7SOiNpRqKLytLk+GHUSE0hkpX+kLi7F+9ai1FvlJDYOCU1WbGba1d+NH1hfaD/eKkuknluPwJv3fEv9DOeYRk6xuv9HOrlY7medCRH75hCG0XPl7hdbLyHHfaknnp618IOhLHExeyB5jHFpH14fmyGmFomVRyAEuW/ALcBlFD1otllxg1Nvd9Nqd7q7NcG11IZ6Pu4ypccXlT0xwttWLCgU6aGWjXr6WeVxaGA8s+UO2q7ihbLt/frQc5IEPMPr/sfT8TJc5Yv+hDgiGSyTl/8pwQbBUsUYNiowJ5l3T1bm04nJInpIGHdpigrv/MiQtxGEUNJTvA5z0oUQR0KlqAGhZg+5S7RH0T9Y3CP246qGKhJRnZwCU4JDRcmPZXyDX9jhc6NvV+4Kdok792pthdfcmxcjLvPp8e7At35cA756JMfH2MNBTL1sdJcaHLyBVzgVSKX96+XnvWK3yE1tOJ15PyGKrudzlpR5GA4JFSatb3vrPasjNF9TiJ+svlD0Fclb1UTHZye9FeO7syW5GpNhubXedYgtj7dXqYIIs5ZD5ups7FJgln6Thl9z0ftKJn1G1C3qW9kXAl1l9bHr5oQYnx8ItxKTg=
  file:
    - dist/ef-core.min.js
    - dist/ef-core.min.js.map
    - dist/ef-core.dev.js
    - dist/ef-core.dev.js.map
  skip_cleanup: true
  on:
    tags: true
- provider: npm
  email: syqlds@126.com
  api_key:
    secure: N1DYMKgCMR/urhhtNEKvNg1HdjvcMg3UMFwPkWaHIdDAVDUHpYgurUMUbSbxGRUdQCQ0J5d10bAPFf++jsaoOzhsL2knvp+HQzoko7vyRBIsv17OT1En0uNH/OZj2qb3zIDCfJPGhCxy+miOwv9S2nQgthBCoT3u1nyWhQCqGkTKIBbALV6YjleKVzS3OAwu/9+TjDMY9y6sJMfVv81zv5I4JAQMqDBoxhIkfT3cVjZh52dowAkmG9WHglTSz8KmhdhOer5HwOGTY7Mvq6Diu8tkRW/SiG706F3TDzx0Sh1SXkI4BsUE2seSuyIYel5wNN9Rhyqp2/ZQJbExLNWZ05QHRsV3OkRGNCGaMBTHM10qbBgHBfLv3bvt+TFenAMJh3Y+wrRIkAtkNqOUdeMHuJAk2yh+KWpYEWmRlBaPWBlztTAp9vdxQbF97704vLqDyl3SwaPZ5O71F+XSOFd1LUaxgCDDmxRMzNlLExACevE9Uols8cuuMv/gzRpjNOZecR8yqjV1KTrfdS3KF9GKL0yLc7BYt21v31jUwLUpOq0msFHQotpa6cZld2wFIV7ZrMk/1em2AKigAiOgtX3DZNruTIhDJtXTl2v3plihDY6XaMnQN/XCdvRLxwa+lKMtWctAx27XXZC0fmCmuv0cMHEPCbwt3wD4n74fD2588uA=
  skip_cleanup: true
  on:
    tags: true
